% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 19-Aug-2023 21:02:36
%
% This script assumes these variables are defined:
%
%   buttinputs - input data.
%   butttorques - target data.

x = buttinputs;
t = butttorques;

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainbr';  % Levenberg-Marquardt backpropagation.

% Create a Fitting Network
hiddenLayerSize = 8;
ffnn_net = fitnet(hiddenLayerSize,trainFcn);

% Setup Division of Data for Training, Validation, Testing
ffnn_net.divideParam.trainRatio = 70/100;
ffnn_net.divideParam.valRatio = 15/100;
ffnn_net.divideParam.testRatio = 15/100;

% Train the Network
[ffnn_net,tr] = train(ffnn_net,x,t);

% Test the Network
y = ffnn_net(x);
e = gsubtract(t,y);
performance = perform(ffnn_net,t,y)

% View the Network
view(ffnn_net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)

